### ISSUE TITLE
Different Lists and Broken Lists

### ISSUE THREAD

**Issue by domsl** [deathau/80s-Neon-for-Obsidian.md#1]
Hi, I really love your CSS style, it looks beautiful!

I just wanted to report to problems with the lists in markdown:

Firstly, there is no difference between a - and *?
![image](https://user-images.githubusercontent.com/10066244/82055271-8657a700-96c0-11ea-8401-41b4b858b1a7.png)

And also you can somehow break them?
![image](https://user-images.githubusercontent.com/10066244/82055324-9b343a80-96c0-11ea-9d2a-9e43d6b87e87.png)

Unfortunately I have no clue about css to investigate it any further. :)

**Comment by deathau** [comment]
Thanks for the report, the weird spacing issue is fixed.

As for there being no difference between a `-` and a `*`, that is just markdown. `-`, `*` and `+` all just convert to the same kind of bulleted list.

**Comment by domsl** [comment]
Great thanks!
