### ISSUE TITLE
List Checkbox Spacer

### ISSUE THREAD

**Issue by chi-wi** [deathau/80s-Neon-for-Obsidian.md#3]
Hey!
I really love your funky theme :) You did an amazing job on it!
However, there should definitely be a space between the checkbox and the text.

Currently, it's looking like this:
![image](https://user-images.githubusercontent.com/68564120/92166257-9a264500-ee38-11ea-875b-fc8a5b2cfb4c.png)

I edited the obsidian.css this way (very very ugly I imagine and as soon as somebody changes the font size the space is broken)
.markdown-preview-view .task-list-item-checkbox {
    -webkit-appearance: none;
    box-sizing: border-box;
    border: 1px solid  var(--accent-2);
    position: relative;
    width: 1.25em;
    height: 1.25em;
    margin: 0;
    **`margin-right: 10px;`**
    box-shadow: 0 0 0.5em var(--accent-2);
}

It now looks like this:

![image](https://user-images.githubusercontent.com/68564120/92166689-5122c080-ee39-11ea-9de8-a9d300b4d61e.png)

Hope you can insert a space between the box and text in the next iteration!

Keep up the good work :)

**Comment by deathau** [comment]
Thanks, @chi-wi, This isn't my default theme, so I hadn't noticed. It's fixed now, so you should be able to update (or reapply the community theme).
