### ISSUE TITLE
Titlebar-text is completely black

### ISSUE THREAD

**Issue by Gorpalicious** [deathau/80s-Neon-for-Obsidian.md#6]
May just be my machine but it was showing as completely black so I couldn't actually see what I'm clicking on.

It seems to be this class:
<div class="titlebar-text">Obsidian 0.8.14</div>

And I it made it visible again (middlebar text = white, right-hand side icons = dark grey) by disabling this css:
text-on-accent: rgba(0,0,0,0.8);

(Love this theme by the way)

**Comment by deathau** [comment]
Could you provide a screenshot?
This is what I see in 0.8.14:
![image](https://user-images.githubusercontent.com/1421840/93569033-5a349580-f9d4-11ea-8cd5-c058ed685a7a.png)
Also, you might want to double-check that you have the latest update, because the titlebar class did change in 0.8.14 (and I did fix that).

**Comment by Gorpalicious** [comment]
[Before](https://user-images.githubusercontent.com/33858764/93571226-0d2cd100-f98c-11ea-8050-84aaf9b19c16.png)
[After](https://user-images.githubusercontent.com/33858764/93571126-ec647b80-f98b-11ea-8573-39ea66236189.png)

Just turned the theme off and on again and it's fixed 🤦 Thanks for such a quick response, sorry for wasting your time

**Comment by Gorpalicious** [comment]
[Before](https://user-images.githubusercontent.com/33858764/93571226-0d2cd100-f98c-11ea-8050-84aaf9b19c16.png)
[After](https://user-images.githubusercontent.com/33858764/93571126-ec647b80-f98b-11ea-8573-39ea66236189.png)

Just turned the theme off and on again and it's fixed 🤦 Thanks for such a quick response, sorry for wasting your time
