### ISSUE TITLE
Code not always in theme colours

### ISSUE THREAD

**Issue by izzylys** [deathau/80s-Neon-for-Obsidian.md#8]
Heya,

Totally love this theme and have been using it as my main one! Thanks a lot for this ✨

One thing that has been bothering me is that inline code in preview and code blocks in editing show up red which doesn't really vibe with the main theme colour palette (and the red is a bit stressful to me!). I'm not sure if this was intentional, but if not (and if you're cool contributions) I can make a quick PR to use the theme colours for this.

Screenshot of what I'm talking about:
![image](https://user-images.githubusercontent.com/7717434/95357545-e5ac9280-08bf-11eb-81ff-5d162710b2d1.png)

**Comment by deathau** [comment]
Thanks for pointing this out — and for providing a fix 😄
